changed all class based components to functional based
A00020061/crypto-app pull request #12
Opened 2022-12-31 05:26 UTC by A00020061

All class based components have been changed into functional based components.

2023-01-02 00:58 UTC, yoloOnTheBattlefield requested changes

2023-01-02 00:58 UTC, yoloOnTheBattlefield commented on src/Components/Charts/charts.js
> +              // alert2={this.props.alert2}
remove this

2023-01-02 00:58 UTC, yoloOnTheBattlefield commented on src/Components/Navbar/index.styles.js
> +  } */
remove this

2023-01-02 00:58 UTC, yoloOnTheBattlefield commented on src/Components/Navbar/index.styles.js
> +  } */
and this

2023-01-02 00:58 UTC, yoloOnTheBattlefield commented on src/Pages/CoinPage/CoinPage.js
> +      console.log("hello", response.data);
remove this

2023-01-04 14:04 UTC, A00020061 commented on src/Components/Charts/charts.js
> +              // alert2={this.props.alert2}
removed

2023-01-04 14:05 UTC, A00020061 commented on src/Components/Navbar/index.styles.js
> +  } */
removed

2023-01-04 14:05 UTC, A00020061 commented on src/Components/Navbar/index.styles.js
> +  } */
removed

2023-01-04 14:05 UTC, A00020061 commented on src/Pages/CoinPage/CoinPage.js
> +      console.log("hello", response.data);
removed

2023-01-04 14:05 UTC, merged