Added coinpage with functionality
A00020061/crypto-app pull request #13
Opened 2023-01-04 14:08 UTC by A00020061

Added coinpage functionality

2023-01-04 21:54 UTC, yoloOnTheBattlefield requested changes

2023-01-04 21:54 UTC, yoloOnTheBattlefield commented on src/App.js
>                <Route path="/Setting" exact component={Setting} />
use lowercase like /setting or /coinpage/:coinName

2023-01-04 21:54 UTC, yoloOnTheBattlefield commented on src/Components/Charts/charts.styles.js
> +  /* border: solid white; */
delete

2023-01-04 21:54 UTC, yoloOnTheBattlefield commented on src/services/action/coinNameAction.js
> +  // console.log("you clicked me just now");
delete

2023-01-05 01:04 UTC, A00020061 commented on src/App.js
>                <Route path="/Setting" exact component={Setting} />
implemented

2023-01-05 01:04 UTC, merged