created portfolio page without full functionality
A00020061/crypto-app pull request #14
Opened 2023-01-18 15:13 UTC by A00020061

2023-01-18 23:16 UTC, yoloOnTheBattlefield requested changes

2023-01-18 23:16 UTC, yoloOnTheBattlefield commented on src/Components/portfolio/mainPage.js
> +  console.log(list);
remove console

2023-01-18 23:16 UTC, yoloOnTheBattlefield commented on src/Components/portfolio/popForm.js
> +      alert("Are you sure want to leave the form?");
don;t use alerts bro,

2023-01-19 04:52 UTC, A00020061 commented on src/Components/portfolio/popForm.js
> +      alert("Are you sure want to leave the form?");
removed

2023-01-19 04:52 UTC, merged