fetch top 10 coins
A00020061/crypto-app pull request #8
Opened 2022-12-07 15:32 UTC by A00020061

Top 10 coins displayed under click buttons

2022-12-07 19:45 UTC, yoloOnTheBattlefield requested changes

2022-12-07 19:45 UTC, yoloOnTheBattlefield commented on src/Components/Charts/ChooseCoin/SelectCoin.js
> +      <li id="365">1 year</li>
you can use data for this like an array

2022-12-07 19:45 UTC, yoloOnTheBattlefield commented on src/Components/Charts/ChooseCoin/SelectCoin.js
> +    // );
remove this

2022-12-12 06:38 UTC, A00020061 commented on src/Components/Charts/ChooseCoin/SelectCoin.js
> +    // );
removed

2022-12-12 06:38 UTC, merged